# our base image
FROM nginx:1.14-alpine

# Hægt að afrita beint inn html skjölin. Eða með því að sleppa þessu að mappa frekar
# drif af host diski með docker run (sjá readme.txt).
# COPY static-html-directory /usr/share/nginx/html

